// Builds conquest/data/geo.js and conquest/data/height.png from Natural Earth
// (public domain) vectors and a NASA elevation bump map.
// Usage: node build_geo.mjs <dir-with-sources> <node_modules dir>
import fs from 'fs';
import path from 'path';
import { createRequire } from 'module';

const [, , SRC, NM] = process.argv;
const require = createRequire(path.join(NM, 'x.js'));
const jpeg = require('jpeg-js');
const { PNG } = require('pngjs');

const BBOX = { lon0: -11, lon1: 50, lat0: 27, lat1: 64 };
const M = 3; // clamp margin in degrees
const OUT = path.resolve(path.dirname(new URL(import.meta.url).pathname), '../data');

const clampPt = ([x, y]) => [
  Math.min(BBOX.lon1 + M, Math.max(BBOX.lon0 - M, x)),
  Math.min(BBOX.lat1 + M, Math.max(BBOX.lat0 - M, y)),
];

function dp(pts, eps) {
  if (pts.length < 3) return pts;
  const f = pts[0], l = pts[pts.length - 1];
  if (f[0] === l[0] && f[1] === l[1]) {
    const m = pts.length >> 1;
    return dp(pts.slice(0, m + 1), eps).slice(0, -1).concat(dp(pts.slice(m), eps));
  }
  const keep = new Uint8Array(pts.length);
  keep[0] = keep[pts.length - 1] = 1;
  const stack = [[0, pts.length - 1]];
  while (stack.length) {
    const [a, b] = stack.pop();
    const [ax, ay] = pts[a], [bx, by] = pts[b];
    const dx = bx - ax, dy = by - ay, L = Math.hypot(dx, dy) || 1e-9;
    let md = 0, mi = -1;
    for (let i = a + 1; i < b; i++) {
      const d = Math.abs((pts[i][0] - ax) * dy - (pts[i][1] - ay) * dx) / L;
      if (d > md) { md = d; mi = i; }
    }
    if (md > eps && mi > 0) { keep[mi] = 1; stack.push([a, mi], [mi, b]); }
  }
  return pts.filter((_, i) => keep[i]);
}

const inBox = (bb) => !(bb[2] < BBOX.lon0 - M || bb[0] > BBOX.lon1 + M || bb[3] < BBOX.lat0 - M || bb[1] > BBOX.lat1 + M);
const ringBox = (r) => {
  let a = 1e9, b = 1e9, c = -1e9, d = -1e9;
  for (const [x, y] of r) { a = Math.min(a, x); b = Math.min(b, y); c = Math.max(c, x); d = Math.max(d, y); }
  return [a, b, c, d];
};
const flat = (r) => r.flatMap(([x, y]) => [+x.toFixed(3), +y.toFixed(3)]);

function polys(file, eps, minArea = 0) {
  const g = JSON.parse(fs.readFileSync(path.join(SRC, file)));
  const out = [];
  for (const f of g.features) {
    const geom = f.geometry;
    if (!geom) continue;
    const ps = geom.type === 'Polygon' ? [geom.coordinates] : geom.coordinates;
    for (const p of ps) {
      const ring = p[0];
      const bb = ringBox(ring);
      if (!inBox(bb)) continue;
      if ((bb[2] - bb[0]) * (bb[3] - bb[1]) < minArea) continue;
      const rings = [];
      for (const raw of p) {
        if (raw !== ring && !inBox(ringBox(raw))) continue;
        let r = raw.map(clampPt).filter((q, i, a) => i === 0 || q[0] !== a[i - 1][0] || q[1] !== a[i - 1][1]);
        r = dp(r, eps);
        if (r.length >= 4) rings.push(flat(r));
      }
      if (rings.length) out.push(rings);
    }
  }
  return out;
}

const land = polys('ne_10m_land.geojson', 0.012, 0.0004);
const lakesG = JSON.parse(fs.readFileSync(path.join(SRC, 'ne_10m_lakes.geojson')));
const lakes = [];
for (const f of lakesG.features) {
  if (f.properties.scalerank > 6) continue;
  const ps = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const p of ps) {
    const bb = ringBox(p[0]);
    if (!inBox(bb) || (bb[2] - bb[0]) * (bb[3] - bb[1]) < 0.02) continue;
    lakes.push(flat(dp(p[0].map(clampPt), 0.01)));
  }
}
const rivG = JSON.parse(fs.readFileSync(path.join(SRC, 'ne_10m_rivers_lake_centerlines.geojson')));
const rivers = [];
for (const f of rivG.features) {
  const sr = f.properties.scalerank;
  if (sr > 7 || f.properties.featurecla === 'Lake Centerline') continue;
  const ls = f.geometry.type === 'LineString' ? [f.geometry.coordinates] : f.geometry.coordinates;
  for (const l of ls) {
    const bb = ringBox(l);
    if (!inBox(bb)) continue;
    const s = dp(l, 0.015);
    if (s.length >= 2) rivers.push({ r: sr, n: f.properties.name || '', p: flat(s) });
  }
}

fs.writeFileSync(path.join(OUT, 'geo.js'),
  '// Generated by tools/build_geo.mjs from Natural Earth (public domain). Do not edit.\n' +
  `export const GEO = ${JSON.stringify({ bbox: BBOX, land, lakes, rivers })};\n`);

// Elevation crop (equirectangular source, 4096x2048)
const img = jpeg.decode(fs.readFileSync(path.join(SRC, 'elev.jpg')));
const W = img.width, H = img.height;
const x0 = Math.floor((BBOX.lon0 - M + 180) / 360 * W), x1 = Math.ceil((BBOX.lon1 + M + 180) / 360 * W);
const y0 = Math.floor((90 - (BBOX.lat1 + M)) / 180 * H), y1 = Math.ceil((90 - (BBOX.lat0 - M)) / 180 * H);
const png = new PNG({ width: x1 - x0, height: y1 - y0 });
for (let y = y0; y < y1; y++) for (let x = x0; x < x1; x++) {
  const s = (y * W + x) * 4, d = ((y - y0) * (x1 - x0) + (x - x0)) * 4;
  png.data[d] = png.data[d + 1] = png.data[d + 2] = img.data[s]; png.data[d + 3] = 255;
}
fs.writeFileSync(path.join(OUT, 'height.png'), PNG.sync.write(png));
fs.writeFileSync(path.join(OUT, 'height.json'), JSON.stringify({
  lon0: x0 / W * 360 - 180, lon1: x1 / W * 360 - 180, lat1: 90 - y0 / H * 180, lat0: 90 - y1 / H * 180,
  w: x1 - x0, h: y1 - y0 }));
console.log('land', land.length, 'pts', land.reduce((a, r) => a + r.length / 2, 0), 'lakes', lakes.length, 'rivers', rivers.length);
